version: '2'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8888:8888 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - database         
    networks:
      - fullstack


  database:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=uber
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

volumes:
  api:
  database_postgres:   

# Networks to be created to facilitate communication between containers

networks:
  fullstack:
        driver: bridge
        ipam:
            driver: default
            config:
              - subnet: 172.16.1.0/24
      